#!/bin/sh -eux

ub_install

cd ${UB_INSTALLDIR}/usr/lib
ln -s libgio-2.0.so.0.4400.1 libgio-2.0.so.0.4000.0
ln -s libglib-2.0.so.0.4400.1 libglib-2.0.so.0.4000.0
ln -s libgmodule-2.0.so.0.4400.1 libgmodule-2.0.so.0.4000.0
ln -s libgobject-2.0.so.0.4400.1 libgobject-2.0.so.0.4000.0
ln -s libgthread-2.0.so.0.4400.1 libgthread-2.0.so.0.4000.0
