#!/bin/sh -eux

ub_install

find "$UB_INSTALLDIR"/usr/share -type f -exec chmod 0644 {} \;
rm -f "$UB_INSTALLDIR"/usr/bin/{aptik-launcher,aptik-uninstall}
mv "$UB_INSTALLDIR"/usr/bin/{aptik,aptik-gtk} "$UB_INSTALLDIR"/usr/sbin/
