#!/bin/sh -eux

ub_install

install -D -m0644 examples/thinkfan.conf.simple "$UB_INSTALLDIR"/etc/thinkfan.conf
install -D -m0644 rcscripts/thinkfan.service "$UB_INSTALLDIR"/lib/systemd/system/thinkfan.service
